name: Deploy by DNScontrol

on:
  push:
    branches:
      - main
    paths:
      - "dnscontrol/staging/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GCLOUD_KEY: ${{ secrets.DNSCONTROL_GCP_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Put creds.json
        run: echo "$GCLOUD_KEY" > dnscontrol/staging/creds.json

      - name: DNSControl push
        uses: koenrh/dnscontrol-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: push
          config_file: 'dnscontrol/staging/dnsconfig.js'
          creds_file: 'dnscontrol/staging/creds.json'
