name: Apply by Terraform

on:
  push:
    branches:
      - "main"
    paths:
      - 'terraform/**'

jobs:
  apply:
    name: "Apply by Terraform"
    runs-on: ubuntu-latest
    env:
      GCLOUD_KEY: ${{ secrets.TERRAFORM_GCP_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: echo "$GCLOUD_KEY" > terraform/gcloud-credential.json
      - name: "Terraform Apply"
        id: apply
        working-directory: terraform
        run: terraform apply -auto-approve -no-color
