name: Apply by Terraform

on:
  push:
    branches:
      - "main"
    paths:
      - 'terraform/**'

defaults:
  run:
    working-directory: terraform

jobs:
  apply:
    name: "Apply by Terraform"
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.TERRAFORM_GCP_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: "Terraform Apply"
        id: apply
        run: terraform apply -auto-approve -no-color
